stages:
- build

build_branches:
  image: maven:3.5.2-jdk-8-alpine
  stage: build
  script:
  # Parameter -B is "non-interactive"
  - mvn clean dependency:tree package -B -X

  artifacts:
    expire_in: 1 week
    paths:
    - target/*.jar
  only:
  - branches
  except:
  - master

build_master:
  image: maven:3.5.2-jdk-8-alpine
  stage: build
  script:
  # Parameter -B is "non-interactive"
  - mvn clean dependency:tree package -B -X
  artifacts:
    paths:
    - target/*.jar
  only:
  - master